# Generated by Django 5.2.8 on 2025-11-15 19:35

import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("umap", "0028_map_is_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerPoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("state", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="umap.datalayer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("file", sorl.thumbnail.fields.ImageField(upload_to="")),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "layer_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="galerie.layerpoint",
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
