# Generated by Django 5.2.8 on 2025-12-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_squashed_0012_alter_layerpoint_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerpoint',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
