# Generated by Django 5.2.8 on 2025-12-14 00:13

import sorl.thumbnail.fields
import umap.galerie.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galerie", "0013_layerpoint_json_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="file",
            field=sorl.thumbnail.fields.ImageField(
                upload_to=umap.galerie.models.get_upload_name
            ),
        ),
    ]
