# Generated by Django 5.2.8 on 2025-12-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galerie", "0014_alter_picture_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={"ordering": ["-datetime", "-upload_date"]},
        ),
    ]
